"""Generate Triton kernels for equivariant linear maps and their derivatives.

The generated module contains one layout slot per supported tensor rank.
The rowwise kernel computes ``(A_l @ op(W_l) + B_l @ op(V_l)) * scale_l``,
with either term enabled as needed. The weight-gradient kernel computes
``scale_l * grad_out_l.T @ B_l``. These two operations also supply the
products needed when differentiating the backward calculation.

Each program selects a tensor-rank slot. Compile-time guards remove
inactive ranks. Rowwise outputs use independent stores. Weight gradients
also use independent stores unless the row reduction is divided between
programs, in which case contributions are added atomically. Autotuning
resets outputs that accumulate contributions between trial launches.

Configuration filters limit float64 accumulator tiles and estimate shared
memory required by pipelined matrix-product inputs. If no shared-memory
configuration fits, the smallest estimate is retained so Triton can report
the allocation failure. Filtering avoids failed tuning trials retaining
GPU tensors in exception tracebacks.

The Python module ``flashcart.o3._linear`` loads the generated source from the
cache, supplies layout metadata, and registers the operations with PyTorch.
"""

from typing import List

_MODULE_DOCSTRING = '"""Auto-generated by flashcart.o3._codegen_linear.build_triton_linear_module_source."""'

_ROWWISE_CONFIGS_SOURCE = """\
_LINEAR_ROWWISE_AUTOTUNE_CONFIGS = [
    triton.Config({"BLOCK_ROWS": 64, "BLOCK_OUT": 128, "BLOCK_K": 32}, num_warps=4),
    triton.Config({"BLOCK_ROWS": 128, "BLOCK_OUT": 128, "BLOCK_K": 64}, num_warps=8, num_stages=3),
    triton.Config({"BLOCK_ROWS": 64, "BLOCK_OUT": 64, "BLOCK_K": 32}, num_warps=4),
    triton.Config({"BLOCK_ROWS": 32, "BLOCK_OUT": 32, "BLOCK_K": 32}, num_warps=2),
    triton.Config({"BLOCK_ROWS": 32, "BLOCK_OUT": 64, "BLOCK_K": 32}, num_warps=2),
    # Un-capped configs can saturate the register ceiling with all l-slot
    # bodies inlined; maxnreg trades mild spilling for higher occupancy.
    triton.Config({"BLOCK_ROWS": 64, "BLOCK_OUT": 128, "BLOCK_K": 32}, num_warps=4, maxnreg=128),
]
"""

_WGRAD_CONFIGS_SOURCE = """\
_LINEAR_WGRAD_AUTOTUNE_CONFIGS = [
    triton.Config({"BLOCK_FOUT": 32, "BLOCK_FIN": 32, "BLOCK_K": 32}, num_warps=2),
    triton.Config({"BLOCK_FOUT": 64, "BLOCK_FIN": 64, "BLOCK_K": 32}, num_warps=4),
    triton.Config({"BLOCK_FOUT": 64, "BLOCK_FIN": 64, "BLOCK_K": 64}, num_warps=4, num_stages=3),
    triton.Config({"BLOCK_FOUT": 32, "BLOCK_FIN": 64, "BLOCK_K": 64}, num_warps=4, num_stages=2),
    triton.Config({"BLOCK_FOUT": 64, "BLOCK_FIN": 32, "BLOCK_K": 64}, num_warps=4),
    triton.Config({"BLOCK_FOUT": 64, "BLOCK_FIN": 64, "BLOCK_K": 32}, num_warps=4, maxnreg=128),
]
"""

_STATIC_SOURCE = '''\
def _prune_fp64_tiles(configs, named_args, **kwargs):
    """Limit float64 accumulator tiles to reduce register use.

    Prefer configurations with at most 4096 output accumulator elements. If none
    satisfies this limit, retain the original configurations.
    """
    use_fp64 = named_args.get("USE_FP64", kwargs.get("USE_FP64", False))
    if use_fp64:
        small = [c for c in configs if c.kwargs["BLOCK_ROWS"] * c.kwargs["BLOCK_OUT"] <= 64 * 64]
        return small or configs
    return configs


def _smem_limit_bytes():
    """Shared-memory-per-block limit of the current device."""
    active = triton.runtime.driver.active
    return active.utils.get_device_properties(active.get_current_device())["max_shared_mem"]


def _prune_smem_exceeding(configs, named_args, **kwargs):
    """Filter configurations using an estimate of shared-memory use.

    The estimate includes pipelined matrix-product input tiles and the number of active
    terms. Configurations exceeding the device limit are removed. If none fits, retain
    the configuration with the smallest estimate and let Triton report any allocation
    failure.

    Filtering before launch avoids retaining GPU tensors through exception tracebacks
    produced by failed autotuning trials.
    """
    def _flag(name):
        return bool(named_args.get(name, kwargs.get(name, False)))

    elt_bytes = 8 if _flag("USE_FP64") else 4
    # rowwise loads an (A, W) tile pair per active term; wgrad loads (go, b) once.
    n_terms = max(int(_flag("TERM1")) + int(_flag("TERM2")), 1)

    def _smem_bytes(config):
        kw = config.kwargs
        block_k = kw["BLOCK_K"]
        if "BLOCK_ROWS" in kw:
            tile_elems = n_terms * block_k * (kw["BLOCK_ROWS"] + kw["BLOCK_OUT"])
        else:
            tile_elems = block_k * (kw["BLOCK_FOUT"] + kw["BLOCK_FIN"])
        return max(config.num_stages - 1, 1) * tile_elems * elt_bytes

    limit = _smem_limit_bytes()
    fits = [c for c in configs if _smem_bytes(c) <= limit]
    # An empty list is an autotuner error; the smallest-footprint config at
    # least degrades gracefully through triton's own OutOfResources path.
    return fits or [min(configs, key=_smem_bytes)]


def _prune_rowwise_configs(configs, named_args, **kwargs):
    configs = _prune_fp64_tiles(configs, named_args, **kwargs)
    return _prune_smem_exceeding(configs, named_args, **kwargs)


@triton.jit
def _dot_acc(acc, a, b, USE_FP64: tl.constexpr, INPUT_PRECISION: tl.constexpr):
    if USE_FP64:
        return acc + tl.dot(a, b)
    else:
        return acc + tl.dot(a, b, input_precision=INPUT_PRECISION)


@triton.jit
def _load_row_tile(ptr, row_off, k, K: tl.constexpr, row_mask, EVEN_K: tl.constexpr):
    """(BLOCK_ROWS, BLOCK_K) tile of a packed [n, m, K] block."""
    if EVEN_K:
        return tl.load(ptr + row_off[:, None] + k[None, :], mask=row_mask[:, None], other=0.0)
    else:
        return tl.load(
            ptr + row_off[:, None] + k[None, :],
            mask=row_mask[:, None] & (k[None, :] < K),
            other=0.0,
        )


@triton.jit
def _load_weight_tile(
    w_ptr,
    cols,
    k,
    K: tl.constexpr,
    O: tl.constexpr,
    TRANS_W: tl.constexpr,
    EVEN_K: tl.constexpr,
    EVEN_O: tl.constexpr,
):
    """(BLOCK_K, BLOCK_OUT) tile of a row-major weight; TRANS_W selects contraction over
    the trailing (fwd) or leading (dgrad) weight dim.
    """
    if TRANS_W:
        off = cols[None, :] * K + k[:, None]
    else:
        off = k[:, None] * O + cols[None, :]
    if EVEN_K and EVEN_O:
        return tl.load(w_ptr + off)
    elif EVEN_K:
        return tl.load(w_ptr + off, mask=cols[None, :] < O, other=0.0)
    elif EVEN_O:
        return tl.load(w_ptr + off, mask=k[:, None] < K, other=0.0)
    else:
        return tl.load(w_ptr + off, mask=(k[:, None] < K) & (cols[None, :] < O), other=0.0)


@triton.jit
def _rowwise_body(
    a_ptr,
    b_ptr,
    out_ptr,
    w_ptr,
    v_ptr,
    scale_ptr,
    n_batch,
    a_stride_n,
    b_stride_n,
    out_stride_n,
    A_OFF: tl.constexpr,
    O_OFF: tl.constexpr,
    K: tl.constexpr,
    O: tl.constexpr,
    M_L: tl.constexpr,
    TERM1: tl.constexpr,
    TERM2: tl.constexpr,
    TRANS_W: tl.constexpr,
    BLOCK_ROWS: tl.constexpr,
    BLOCK_OUT: tl.constexpr,
    BLOCK_K: tl.constexpr,
    USE_FP64: tl.constexpr,
    INPUT_PRECISION: tl.constexpr,
):
    pid_row = tl.program_id(0)
    pid_out = tl.program_id(1)
    total_rows = n_batch * M_L
    if (pid_row * BLOCK_ROWS < total_rows) & (pid_out * BLOCK_OUT < O):
        EVEN_K: tl.constexpr = K % BLOCK_K == 0
        EVEN_O: tl.constexpr = O % BLOCK_OUT == 0
        rows = pid_row * BLOCK_ROWS + tl.arange(0, BLOCK_ROWS)
        cols = pid_out * BLOCK_OUT + tl.arange(0, BLOCK_OUT)
        row_mask = rows < total_rows
        n = rows // M_L
        m = rows - n * M_L
        if TERM1:
            a_row = n.to(tl.int64) * a_stride_n + A_OFF + m * K
        if TERM2:
            b_row = n.to(tl.int64) * b_stride_n + A_OFF + m * K

        acc_dtype = tl.float64 if USE_FP64 else tl.float32
        acc = tl.zeros((BLOCK_ROWS, BLOCK_OUT), dtype=acc_dtype)
        for k0 in range(0, K, BLOCK_K):
            k = k0 + tl.arange(0, BLOCK_K)
            if TERM1:
                a_t = _load_row_tile(a_ptr, a_row, k, K, row_mask, EVEN_K)
                w_t = _load_weight_tile(w_ptr, cols, k, K, O, TRANS_W, EVEN_K, EVEN_O)
                acc = _dot_acc(acc, a_t, w_t, USE_FP64, INPUT_PRECISION)
            if TERM2:
                b_t = _load_row_tile(b_ptr, b_row, k, K, row_mask, EVEN_K)
                v_t = _load_weight_tile(v_ptr, cols, k, K, O, TRANS_W, EVEN_K, EVEN_O)
                acc = _dot_acc(acc, b_t, v_t, USE_FP64, INPUT_PRECISION)

        acc *= tl.load(scale_ptr)
        out_off = out_ptr + n[:, None].to(tl.int64) * out_stride_n + O_OFF + m[:, None] * O + cols[None, :]
        if EVEN_O:
            tl.store(out_off, acc, mask=row_mask[:, None])
        else:
            tl.store(out_off, acc, mask=row_mask[:, None] & (cols[None, :] < O))


@triton.jit
def _wgrad_body(
    go_ptr,
    b_ptr,
    g_ptr,
    scale_ptr,
    n_batch,
    go_stride_n,
    b_stride_n,
    IN_OFF: tl.constexpr,
    OUT_OFF: tl.constexpr,
    FIN: tl.constexpr,
    FOUT: tl.constexpr,
    M_L: tl.constexpr,
    SPLIT: tl.constexpr,
    BLOCK_FOUT: tl.constexpr,
    BLOCK_FIN: tl.constexpr,
    BLOCK_K: tl.constexpr,
    USE_FP64: tl.constexpr,
    INPUT_PRECISION: tl.constexpr,
):
    pid_t = tl.program_id(0)
    pid_s = tl.program_id(1)
    FIN_TILES: tl.constexpr = (FIN + BLOCK_FIN - 1) // BLOCK_FIN
    FOUT_TILES: tl.constexpr = (FOUT + BLOCK_FOUT - 1) // BLOCK_FOUT
    if pid_t < FIN_TILES * FOUT_TILES:
        EVEN_FIN: tl.constexpr = FIN % BLOCK_FIN == 0
        EVEN_FOUT: tl.constexpr = FOUT % BLOCK_FOUT == 0
        pid_fo = pid_t // FIN_TILES
        pid_fi = pid_t - pid_fo * FIN_TILES
        fo = pid_fo * BLOCK_FOUT + tl.arange(0, BLOCK_FOUT)
        fi = pid_fi * BLOCK_FIN + tl.arange(0, BLOCK_FIN)

        total_rows = n_batch * M_L
        n_split = tl.num_programs(1)
        rows_per_split = tl.cdiv(total_rows, n_split)
        r0 = pid_s * rows_per_split
        r_end = tl.minimum(r0 + rows_per_split, total_rows)

        acc_dtype = tl.float64 if USE_FP64 else tl.float32
        acc = tl.zeros((BLOCK_FOUT, BLOCK_FIN), dtype=acc_dtype)
        for r_base in range(r0, r_end, BLOCK_K):
            r = r_base + tl.arange(0, BLOCK_K)
            r_mask = r < r_end
            n = r // M_L
            m = r - n * M_L
            go_off = go_ptr + n[:, None].to(tl.int64) * go_stride_n + OUT_OFF + m[:, None] * FOUT + fo[None, :]
            b_off = b_ptr + n[:, None].to(tl.int64) * b_stride_n + IN_OFF + m[:, None] * FIN + fi[None, :]
            if EVEN_FOUT:
                go_t = tl.load(go_off, mask=r_mask[:, None], other=0.0)
            else:
                go_t = tl.load(go_off, mask=r_mask[:, None] & (fo[None, :] < FOUT), other=0.0)
            if EVEN_FIN:
                b_t = tl.load(b_off, mask=r_mask[:, None], other=0.0)
            else:
                b_t = tl.load(b_off, mask=r_mask[:, None] & (fi[None, :] < FIN), other=0.0)
            acc = _dot_acc(acc, tl.trans(go_t), b_t, USE_FP64, INPUT_PRECISION)

        acc *= tl.load(scale_ptr)
        out_val = acc.to(g_ptr.dtype.element_ty)
        g_off = g_ptr + fo[:, None] * FIN + fi[None, :]
        if EVEN_FOUT and EVEN_FIN:
            if SPLIT:
                tl.atomic_add(g_off, out_val, sem="relaxed")
            else:
                tl.store(g_off, out_val)
        else:
            g_mask = (fo[:, None] < FOUT) & (fi[None, :] < FIN)
            if SPLIT:
                tl.atomic_add(g_off, out_val, mask=g_mask, sem="relaxed")
            else:
                tl.store(g_off, out_val, mask=g_mask)
'''


def _name_list_literal(names: List[str], indent: str) -> str:
    return "\n".join(f'{indent}"{name}",' for name in names)


def _emit_rowwise_kernel(num_slots: int) -> str:
    lines: List[str] = []
    keys = (
        ["N_ACTIVE_L"]
        + [f"K{i}" for i in range(num_slots)]
        + [f"O{i}" for i in range(num_slots)]
        + ["TERM1", "TERM2", "TRANS_W", "USE_FP64", "INPUT_PRECISION"]
    )
    lines.append("@triton.autotune(")
    lines.append("    configs=_LINEAR_ROWWISE_AUTOTUNE_CONFIGS,")
    lines.append("    key=[")
    lines.append(_name_list_literal(keys, "        "))
    lines.append("    ],")
    lines.append('    prune_configs_by={"early_config_prune": _prune_rowwise_configs},')
    lines.append(")")
    lines.append("@triton.jit")
    lines.append("def linear_rowwise_kernel(")
    lines.append("    a_ptr,")
    lines.append("    b_ptr,")
    lines.append("    out_ptr,")
    lines.append("    scale_ptr,")
    for i in range(num_slots):
        lines.append(f"    w{i}_ptr,")
    for i in range(num_slots):
        lines.append(f"    v{i}_ptr,")
    lines.append("    n_batch,")
    lines.append("    a_stride_n,")
    lines.append("    b_stride_n,")
    lines.append("    out_stride_n,")
    lines.append("    N_ACTIVE_L: tl.constexpr,")
    for prefix in ("A_OFF", "O_OFF", "K", "O", "M"):
        for i in range(num_slots):
            lines.append(f"    {prefix}{i}: tl.constexpr,")
    lines.append("    TERM1: tl.constexpr,")
    lines.append("    TERM2: tl.constexpr,")
    lines.append("    TRANS_W: tl.constexpr,")
    lines.append("    BLOCK_ROWS: tl.constexpr,")
    lines.append("    BLOCK_OUT: tl.constexpr,")
    lines.append("    BLOCK_K: tl.constexpr,")
    lines.append("    USE_FP64: tl.constexpr,")
    lines.append("    INPUT_PRECISION: tl.constexpr,")
    lines.append("):")
    lines.append('    """``out_l = (A_l @ op(W_l) [+ B_l @ op(V_l)]) * scale_l`` for all l-blocks')
    lines.append('    in one launch; ``program_id(2)`` selects the l-slot."""')
    lines.append("    pid_l = tl.program_id(2)")
    for i in range(num_slots):
        scale = "scale_ptr" if i == 0 else f"scale_ptr + {i}"
        lines.append(f"    if N_ACTIVE_L >= {i + 1}:")
        lines.append(f"        if pid_l == {i}:")
        lines.append("            _rowwise_body(")
        lines.append(f"                a_ptr, b_ptr, out_ptr, w{i}_ptr, v{i}_ptr, {scale},")
        lines.append("                n_batch, a_stride_n, b_stride_n, out_stride_n,")
        lines.append(f"                A_OFF{i}, O_OFF{i}, K{i}, O{i}, M{i},")
        lines.append(
            "                TERM1, TERM2, TRANS_W, BLOCK_ROWS, BLOCK_OUT, BLOCK_K, USE_FP64, INPUT_PRECISION,"
        )
        lines.append("            )")
    return "\n".join(lines) + "\n"


def _emit_wgrad_kernel(num_slots: int) -> str:
    lines: List[str] = []
    keys = (
        ["N_ACTIVE_L"]
        + [f"FIN{i}" for i in range(num_slots)]
        + [f"FOUT{i}" for i in range(num_slots)]
        + ["SPLIT", "USE_FP64", "INPUT_PRECISION"]
    )
    lines.append("@triton.autotune(")
    lines.append("    configs=_LINEAR_WGRAD_AUTOTUNE_CONFIGS,")
    lines.append("    key=[")
    lines.append(_name_list_literal(keys, "        "))
    lines.append("    ],")
    lines.append("    reset_to_zero=[")
    lines.append(_name_list_literal([f"g{i}_ptr" for i in range(num_slots)], "        "))
    lines.append("    ],")
    lines.append('    prune_configs_by={"early_config_prune": _prune_smem_exceeding},')
    lines.append(")")
    lines.append("@triton.jit")
    lines.append("def linear_wgrad_kernel(")
    lines.append("    go_ptr,")
    lines.append("    b_ptr,")
    lines.append("    scale_ptr,")
    for i in range(num_slots):
        lines.append(f"    g{i}_ptr,")
    lines.append("    n_batch,")
    lines.append("    go_stride_n,")
    lines.append("    b_stride_n,")
    lines.append("    N_ACTIVE_L: tl.constexpr,")
    for prefix in ("IN_OFF", "OUT_OFF", "FIN", "FOUT", "M"):
        for i in range(num_slots):
            lines.append(f"    {prefix}{i}: tl.constexpr,")
    lines.append("    SPLIT: tl.constexpr,")
    lines.append("    BLOCK_FOUT: tl.constexpr,")
    lines.append("    BLOCK_FIN: tl.constexpr,")
    lines.append("    BLOCK_K: tl.constexpr,")
    lines.append("    USE_FP64: tl.constexpr,")
    lines.append("    INPUT_PRECISION: tl.constexpr,")
    lines.append("):")
    lines.append('    """``dW_l = scale_l * go_l^T @ B_l`` for all l-blocks in one launch; each')
    lines.append("    program owns one weight tile (deterministic ``tl.store``) unless SPLIT")
    lines.append('    partitions the row reduction across ``program_id(1)`` via atomics."""')
    lines.append("    pid_l = tl.program_id(2)")
    for i in range(num_slots):
        scale = "scale_ptr" if i == 0 else f"scale_ptr + {i}"
        lines.append(f"    if N_ACTIVE_L >= {i + 1}:")
        lines.append(f"        if pid_l == {i}:")
        lines.append("            _wgrad_body(")
        lines.append(f"                go_ptr, b_ptr, g{i}_ptr, {scale},")
        lines.append("                n_batch, go_stride_n, b_stride_n,")
        lines.append(f"                IN_OFF{i}, OUT_OFF{i}, FIN{i}, FOUT{i}, M{i},")
        lines.append("                SPLIT, BLOCK_FOUT, BLOCK_FIN, BLOCK_K, USE_FP64, INPUT_PRECISION,")
        lines.append("            )")
    return "\n".join(lines) + "\n"


def build_triton_linear_module_source(kernel_l_max: int) -> str:
    """Generate a Triton equivariant linear module as Python source.

    Args:
        kernel_l_max (int): Maximum tensor rank included in the generated module.

    Returns:
        str: Python module source. The cache layer adds the fingerprint header
            when writing the module.
    """
    if kernel_l_max < 0:
        raise ValueError(f"kernel_l_max must be >= 0, got {kernel_l_max}.")
    num_slots = kernel_l_max + 1
    pieces = [
        _MODULE_DOCSTRING + "\n",
        "\n",
        "import triton\n",
        "import triton.language as tl\n",
        "\n",
        f"KERNEL_L_MAX = {kernel_l_max}\n",
        f"NUM_L_SLOTS = {num_slots}\n",
        "\n",
        _ROWWISE_CONFIGS_SOURCE,
        "\n",
        _WGRAD_CONFIGS_SOURCE,
        "\n\n",
        _STATIC_SOURCE,
        "\n\n",
        _emit_rowwise_kernel(num_slots),
        "\n\n",
        _emit_wgrad_kernel(num_slots),
    ]
    return "".join(pieces)
